---
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger the action on pushes to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build the project (optional, if using a build step)
      # Uncomment and customize this section if necessary:
      # - name: Install dependencies and build
      #   run: |
      #     npm install
      #     npm run build

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Change this if your output directory differs
          destination_branch: gh-pages
